spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/youtube_db
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    elasticsearch:
      uris: ${ELASTICSEARCH_HOST:localhost:9200}   # ← 환경변수 없으면 localhost:9200 사용
      repositories:
        enabled: true

  redis:
    host: localhost
    port: 6379

jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000
springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs