spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/youtube_db
    username: postgres
    password: pass1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true           # 콘솔에 SQL 쿼리 보여줌
    properties:
      hibernate:
        format_sql: true     # SQL 예쁘게 출력

  data:
    elasticsearch:
      cluster-nodes: localhost:9200     # ES 기본 포트
      repositories:
        enabled: true
